// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class OnBoardingViewConrtoller : UIViewController
	{
		public OnBoardingViewConrtoller (IntPtr handle) : base (handle)
		{
		}
	}
}
