// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using MonoTouch.CoreGraphics;
using Domain.Media;

namespace BeeBaby
{
	public partial class CollectionViewCell : UICollectionViewCell
	{
		public UIImage Image
		{
			get
			{ 
				return this.p_imageView.Image; 
			}
			set
			{
				p_imageView = new UIImageView(new RectangleF(0, 0, MediaBase.ImageThumbnailWidth, MediaBase.ImageThumbnailHeight));
				p_imageView.Image = value;
				ContentView.AddSubview(p_imageView);
			}
		}

		public CollectionViewCell(IntPtr handle) : base(handle)
		{
		}
	}
}
