// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class DealsViewController : UIViewController
	{
		public DealsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			vwWeb.LoadRequest(new NSUrlRequest(new NSUrl("http://grouplighthouse.com")));
		}
	}
}
