// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class EventViewCell : TableViewCell
	{
		public EventViewCell (IntPtr handle) : base (handle)
		{
		}

		public string EventDescription
		{
			get
			{
				return lblEventDesc.Text;
			}
			set
			{
				lblEventDesc.Text = value;;
			}
		}

		public UIImage TagIcon
		{
			get
			{
				return imgEventTagIcon.Image;
			}
			set
			{
				imgEventTagIcon.Image = value;
			}
		}
	}
}
