// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class ImageShareViewController : UIViewController
	{
		public UIImageView BackgroundImageView
		{
			get { return ivwBackgroundImage; }
			set { ivwBackgroundImage = value; }
		}

		public UILabel Label
		{
			get { return lblLabel; }
			set { lblLabel = value; }

		}

		public ImageShareViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
