// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.SlideoutNavigation;

namespace BeeBaby
{
	public partial class MenuViewController : UINavigationController
	{

		public UIWindow Window
		{
			get;
			set;
		}

		public SlideoutNavigationController Menu { get; private set; }


		public MenuViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			UIStoryboard board = UIStoryboard.FromName("MainStoryboard", null);
			UIViewController controller = (UIViewController)board.InstantiateViewController("TimelineViewController");


			Window = new UIWindow (UIScreen.MainScreen.Bounds);
			Menu = new SlideoutNavigationController ();
			Menu.SlideHeight = 9999f;
			Menu.TopView = controller;
			Menu.MenuViewLeft = new LeftMenuViewController ();
//			Menu.MenuViewRight = new DummyControllerRight ();

			Menu.RightMenuEnabled = false;

			Window.RootViewController = Menu;
			Window.MakeKeyAndVisible ();

		}
	}
}
