// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class OverlayViewController : UIViewController
	{
		public OverlayViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
