// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class TimelineMomentCell : UITableViewCell
	{
		public TimelineMomentCell(IntPtr handle) : base(handle)
		{
		}

		public string LabelAge
		{
			get
			{
				return lblAge.Text;
			}
			set
			{
				lblAge.Text = value;
			}
		}

		public string LabelDate
		{
			get
			{
				return lblDate.Text;
			}
			set
			{
				lblDate.Text = value;
			}
		}

		public string LabelEventName
		{
			get
			{
				return lblEventName.Text;
			}
			set
			{
				lblEventName.Text = value;
			}
		}

		public string LabelWhere
		{
			get
			{
				return lblWhere.Text;
			}
			set
			{
				lblWhere.Text = value;
			}
		}

		public string LabelWho
		{
			get
			{
				return lblWho.Text;
			}
			set
			{
				lblWho.Text = value;
			}
		}

		public UIView ViewPhotos
		{
			get
			{
				return vwPhotos;
			}
			set
			{
				vwPhotos = value;
			}
		}
	}
}
