// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BeeBaby
{
	public partial class TimelineEventCell : UITableViewCell
	{
		public TimelineEventCell (IntPtr handle) : base (handle)
		{
		}
	}
}
